steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospringproject", "--build-arg=JAR_FILE=target/myproject-0.0.1-SNAPSHOT.jar", "."]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'cloudrunservice-20220527'
    - '--image'
    - 'gcr.io/$PROJECT_ID/hellospringproject'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
images: ["gcr.io/$PROJECT_ID/hellospringproject"]
